### ISSUE TITLE
New role "rmt"

### ISSUE THREAD

**Issue by jeanmonod** [team-rawbot/rawbot-virtualization#47]
@krtek4, @sephii do you think that it will make sens to create a RMT role? Maybe it could help to spread RMT usage for RVF users...

**Comment by sephii** [comment]
This means we'd absolutely need to have the git config copied in the box so that the commits are done with the correct author. Also I don't feel it's something that's of the box concern but more of the project concern (apart from adding RMT to the project we would install anything else, except perhaps PHP, right?).

**Comment by jeanmonod** [comment]
Yes, this means the ability to be able to commit from the box. But this is already what are doing many RVF users.
And then yes, it related to the project developper tools. But same as for Fabric, but it's more easy to have all the developers tools in the box.

**Comment by krtek4** [comment]
Is RMT installable "globally" like composer is ?

If it is the case, it makes sense to have a role, if he has to live in the project directory, I am a lot less sure.

**Comment by jeanmonod** [comment]
Yes, it's possible: https://github.com/liip/RMT#option-2-composer-global-installation

**Comment by jeanmonod** [comment]
How would you define if it's fits for a role or not?

**Comment by krtek4** [comment]
the PR was merged !
